Repository 1313BAN/team07-stella_trip, pull requests merged in 2025-05, with the labels that each got.

#45 [FE-FEAT] 메인 페이지 api 연결
  front_end/src/App.vue
  front_end/src/components/PlanCard/PlanCard.vue
  front_end/src/components/views/main/TagOverviewSection.vue
  front_end/src/services/api/domains/attraction/index.ts
  front_end/src/services/api/domains/attraction/types.ts
  front_end/src/services/api/domains/auth/types.ts
  front_end/src/services/api/domains/plan/index.ts
  front_end/src/services/api/domains/plan/types.ts
  front_end/src/services/api/endpoint.ts
  front_end/src/services/api/types.ts
  front_end/src/stores/auth.ts
  front_end/src/types/type.ts
Labels: ✨ feature, 🖥️ FE

#43 [BE-FEAT] 인기순 여행 계획 태그 조회 api
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/response/AttractionResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/service/AttractionService.java
  back_end/src/main/java/com/ssafy/stella_trip/common/config/WebConfig.java
  back_end/src/main/java/com/ssafy/stella_trip/dao/plan/PlanDAO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/controller/PlanController.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/TagDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/response/PlanResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/response/TagResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/response/WriterResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/service/PlanService.java
  back_end/src/main/java/com/ssafy/stella_trip/user/service/UserProfileService.java
  back_end/src/main/resources/mappers/Plan.xml
Labels: ✨ feature, 🗄️ BE

#48 [FE-FEAT] suspence and error boundary
  front_end/src/components/AsyncContainer/AsyncContainer.vue
  front_end/src/components/PlanCard/PlanCard.stories.ts
  front_end/src/components/card/AttractionCard/AttractionCard.stories.ts
  front_end/src/components/card/AttractionCard/AttractionCard.vue
  front_end/src/components/card/PlanCard/PlanCard.stories.ts
  front_end/src/components/card/PlanCard/PlanCard.vue
  front_end/src/components/card/StellaCard/StellaCard.stories.ts
  front_end/src/components/card/StellaCard/StellaCard.vue
  front_end/src/components/card/TagCard/TagCard.stories.ts
  front_end/src/components/card/TagCard/TagCard.vue
  front_end/src/components/common/ErrorContent/ErrorContent.stories.ts
  front_end/src/components/common/ErrorContent/ErrorContent.vue
  front_end/src/components/common/GridCardListContainer/GridCardListContainer.stories.ts
  front_end/src/components/common/GridCardListContainer/GridCardListContainer.vue
  front_end/src/components/common/ImageWithFallback/ImageWithFallback.vue
  front_end/src/components/common/RowCardListContainer/RowCardListContainer.stories.ts
  front_end/src/components/skeleton/CardSkeleton/CardSkeleton.stories.ts
  front_end/src/components/skeleton/CardSkeleton/CardSkeleton.vue
  front_end/src/components/skeleton/TagCardSkeleton/TagCardSkeleton.stories.ts
  front_end/src/components/skeleton/TagCardSkeleton/TagCardSkeleton.vue
  front_end/src/components/views/home/IntroductionSection.vue
  front_end/src/components/views/main/AttractionsSection/AttractionsError.vue
  front_end/src/components/views/main/AttractionsSection/AttractionsSection.vue
  front_end/src/components/views/main/AttractionsSection/AttractionsSkeleton.vue
  front_end/src/components/views/main/AttractionsSection/index.ts
  front_end/src/components/views/main/HeroSection.vue
  front_end/src/components/views/main/PopularTagsSection/PopularTagsError.vue
  front_end/src/components/views/main/PopularTagsSection/PopularTagsSection.vue
  front_end/src/components/views/main/PopularTagsSection/PopularTagsSkeleton.vue
  front_end/src/components/views/main/PopularTagsSection/index.ts
  front_end/src/components/views/main/TagOverviewSection.vue
  front_end/src/constants/.gitkeep
  front_end/src/constants/constant.ts
  front_end/src/types/type.ts
  front_end/src/utils/util.ts
  front_end/src/vite-env.d.ts
Labels: ✨ feature, 🖥️ FE

#50 [FEAT-FE] 네비게이션 바 및 모달 컴포넌트 완성 및 로그인 form 추가
  front_end/package-lock.json
  front_end/package.json
  front_end/src/components/Modal/Modal.stories.ts
  front_end/src/components/Modal/Modal.vue
  front_end/src/components/Modal/content/LoginForm.vue
  front_end/src/components/NavigationBar/NavigationBar.stories.ts
  front_end/src/components/NavigationBar/NavigationBar.vue
  front_end/src/components/ui/dialog/Dialog.vue
  front_end/src/components/ui/dialog/DialogClose.vue
  front_end/src/components/ui/dialog/DialogContent.vue
  front_end/src/components/ui/dialog/DialogDescription.vue
  front_end/src/components/ui/dialog/DialogFooter.vue
  front_end/src/components/ui/dialog/DialogHeader.vue
  front_end/src/components/ui/dialog/DialogOverlay.vue
  front_end/src/components/ui/dialog/DialogScrollContent.vue
  front_end/src/components/ui/dialog/DialogTitle.vue
  front_end/src/components/ui/dialog/DialogTrigger.vue
  front_end/src/components/ui/dialog/index.ts
  front_end/src/components/ui/dropdown-menu/DropdownMenu.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuContent.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuGroup.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuItem.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuLabel.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuRadioItem.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuSeparator.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuShortcut.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuSub.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuSubContent.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue
  front_end/src/components/ui/dropdown-menu/DropdownMenuTrigger.vue
  front_end/src/components/ui/dropdown-menu/index.ts
  front_end/src/components/ui/form/FormControl.vue
  front_end/src/components/ui/form/FormDescription.vue
  front_end/src/components/ui/form/FormItem.vue
  front_end/src/components/ui/form/FormLabel.vue
  front_end/src/components/ui/form/FormMessage.vue
  front_end/src/components/ui/form/index.ts
  front_end/src/components/ui/form/injectionKeys.ts
  front_end/src/components/ui/form/useFormField.ts
  front_end/src/components/ui/label/Label.vue
  front_end/src/components/ui/label/index.ts
  front_end/src/services/api/domains/auth/index.ts
  front_end/src/views/Home.vue
Labels: ✨ feature, 🖥️ FE

#54 [BE-FEAT] 시군구 코드 조회 api추가 및 refresh 토큰 로직 수정
  back_end/src/main/java/com/ssafy/stella_trip/attraction/controller/SigunguController.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/SigunguDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/response/GugunResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/response/SidoResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/response/SigunguResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/service/SigunguService.java
  back_end/src/main/java/com/ssafy/stella_trip/dao/sigungu/SigunguDAO.java
  back_end/src/main/java/com/ssafy/stella_trip/security/util/JwtTokenProvider.java
  back_end/src/main/java/com/ssafy/stella_trip/user/controller/UserController.java
  back_end/src/main/java/com/ssafy/stella_trip/user/dto/request/LogoutRequestDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/user/service/UserService.java
  back_end/src/main/resources/mappers/Sigungu.xml
Labels: ✨ feature, 🗄️ BE

#56 [FE-FEAT] 여행 계획 탐색 페이지 레이아웃 및 기본 api 연결
  front_end/src/components/NavigationBar/NavigationBar.vue
  front_end/src/components/ui/button/index.ts
  front_end/src/components/views/attraction/FilteredAttractions/FilteredAttractions.vue
  front_end/src/components/views/attraction/FilteredAttractions/index.ts
  front_end/src/components/views/plan/FilteredPlans/FilteredPlans.vue
  front_end/src/components/views/plan/FilteredPlans/FilteredPlansError.vue
  front_end/src/components/views/plan/FilteredPlans/FilteredPlansSkeleton.vue
  front_end/src/components/views/plan/FilteredPlans/index.ts
  front_end/src/components/views/plan/PlanDetail/AttractionItem.vue
  front_end/src/components/views/plan/PlanDetail/DailySchedule.vue
  front_end/src/components/views/plan/PlanDetail/EmptySchedule.vue
  front_end/src/components/views/plan/PlanDetail/PlanDetail.vue
  front_end/src/components/views/plan/PlanDetail/PlanDetailError.vue
  front_end/src/components/views/plan/PlanDetail/PlanDetailSkeleton.vue
  front_end/src/components/views/plan/PlanDetail/PlanInfo.vue
  front_end/src/components/views/plan/PlanDetail/StellaHeader.vue
  front_end/src/components/views/plan/PlanDetail/index.ts
  front_end/src/components/views/plan/PlanFilter.vue
  front_end/src/composables/useMapState.ts
  front_end/src/composables/usePlanFilter.ts
  front_end/src/router/index.ts
  front_end/src/router/routes.ts
  front_end/src/services/api/domains/plan/index.ts
  front_end/src/services/api/domains/plan/types.ts
  front_end/src/types/kakao.d.ts
  front_end/src/views/Attraction.vue
  front_end/src/views/Plan.vue
  front_end/src/views/PlanDetail.vue
Labels: ✨ feature, 🖥️ FE

#59 [BE-FEAT] 여행지 api 수정사항
  back_end/src/main/java/com/ssafy/stella_trip/attraction/controller/AttractionController.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/ReviewDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/request/ReviewRequestDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/response/AttractionResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/response/ReviewResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/service/AttractionService.java
  back_end/src/main/java/com/ssafy/stella_trip/dao/attraction/AttractionDAO.java
  back_end/src/main/resources/mappers/Attraction.xml
Labels: ✨ feature, 🗄️ BE

#61 [BE-FEAT] 여행계획 조건부 조회 개선
  back_end/src/main/java/com/ssafy/stella_trip/dao/plan/PlanDAO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/controller/PlanController.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/ConstellationDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/response/PlanResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/service/PlanService.java
  back_end/src/main/resources/mappers/Plan.xml
  back_end/src/test/java/com/ssafy/stella_trip/dao/plan/PlanDAOTest.java
Labels: ✨ feature, 🗄️ BE

#69 [BE-FEAT] 채팅방 기능 완성
  back_end/pom.xml
  back_end/src/main/java/com/ssafy/stella_trip/chat/config/WebSocketConfiguration.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/controller/ChatController.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/controller/ChatRoomController.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/dto/ChatDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/dto/ChatMessageDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/dto/ChatRoomDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/dto/response/ChatListResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/dto/response/ChatResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/dto/response/ChatRoomResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/dto/response/RoomListResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/interceptor/JwtChannelInterceptor.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/interceptor/RoomAvailableInterceptor.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/service/ChatRoomService.java
  back_end/src/main/java/com/ssafy/stella_trip/chat/service/ChatService.java
  back_end/src/main/java/com/ssafy/stella_trip/dao/chat/ChatDAO.java
  back_end/src/main/java/com/ssafy/stella_trip/security/dto/JwtUserInfo.java
  back_end/src/main/java/com/ssafy/stella_trip/security/filter/JwtAuthenticationFilter.java
  back_end/src/main/java/com/ssafy/stella_trip/security/util/JwtTokenProvider.java
  back_end/src/main/java/com/ssafy/stella_trip/user/service/UserService.java
  back_end/src/main/resources/mappers/Chat.xml
Labels: ✨ feature, 🗄️ BE

#68 [FE-REFACTOR] kakao map
  front_end/src/components/card/DailyScheduleCard/DailyScheduleCard.stories.ts
  front_end/src/components/card/DailyScheduleCard/DailyScheduleCard.vue
  front_end/src/components/common/AttractionItem/AttractionItem.stories.ts
  front_end/src/components/common/AttractionItem/AttractionItem.vue
  front_end/src/components/common/Constellation/Constellation.vue
  front_end/src/components/map/MapContainer.vue
  front_end/src/components/views/plan/PlanDetail/PlanDetail.vue
  front_end/src/components/views/plan/PlanDetail/PlanInfo.vue
  front_end/src/components/views/plan/PlanDetail/StellaHeader.vue
  front_end/src/composables/useAttractionFilter.ts
  front_end/src/composables/useMap.ts
  front_end/src/composables/useMapMarker.ts
  front_end/src/composables/useMapState.ts
  front_end/src/composables/usePlanFilter.ts
  front_end/src/composables/useScroll.ts
  front_end/src/services/api/domains/plan/types.ts
  front_end/src/types/kakao.d.ts
  front_end/src/utils/mapUtils.ts
  front_end/src/views/PlanDetail.vue
Labels: 🖥️ FE, 🔨 refactor

#71 [BE-FIX] requestbody 형식 camel case로 통일 및 태그 갯수 세는 scheduler 추가
  back_end/src/main/java/com/ssafy/stella_trip/dao/plan/PlanDAO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/request/BasicPlanRequestDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/request/PlanRequestDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/request/PlanScheduleRequestDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/request/RouteInsertRequestDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/request/RouteUpdateRequestDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/request/RoutesUpdateRequestDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/scheduler/TagCountScheduler.java
  back_end/src/main/resources/mappers/Plan.xml
Labels: ✨ feature, 🗄️ BE

#74 Feat/fe/plan modify view
  front_end/src/components/NavigationBar/NavigationBar.vue
  front_end/src/components/card/AddPlanCard/AddPlanCard.stories.ts
  front_end/src/components/card/AddPlanCard/AddPlanCard.vue
  front_end/src/components/card/DailyScheduleCard/DailyScheduleCard.vue
  front_end/src/components/ui/button/index.ts
  front_end/src/components/ui/calendar/Calendar.vue
  front_end/src/components/ui/calendar/CalendarCell.vue
  front_end/src/components/ui/calendar/CalendarCellTrigger.vue
  front_end/src/components/ui/calendar/CalendarGrid.vue
  front_end/src/components/ui/calendar/CalendarGridBody.vue
  front_end/src/components/ui/calendar/CalendarGridHead.vue
  front_end/src/components/ui/calendar/CalendarGridRow.vue
  front_end/src/components/ui/calendar/CalendarHeadCell.vue
  front_end/src/components/ui/calendar/CalendarHeader.vue
  front_end/src/components/ui/calendar/CalendarHeading.vue
  front_end/src/components/ui/calendar/CalendarNextButton.vue
  front_end/src/components/ui/calendar/CalendarPrevButton.vue
  front_end/src/components/ui/calendar/index.ts
  front_end/src/components/ui/checkbox/Checkbox.vue
  front_end/src/components/ui/checkbox/index.ts
  front_end/src/components/ui/popover/Popover.vue
  front_end/src/components/ui/popover/PopoverAnchor.vue
  front_end/src/components/ui/popover/PopoverContent.vue
  front_end/src/components/ui/popover/PopoverTrigger.vue
  front_end/src/components/ui/popover/index.ts
  front_end/src/components/ui/range-calendar/RangeCalendar.vue
  front_end/src/components/ui/range-calendar/RangeCalendarCell.vue
  front_end/src/components/ui/range-calendar/RangeCalendarCellTrigger.vue
  front_end/src/components/ui/range-calendar/RangeCalendarGrid.vue
  front_end/src/components/ui/range-calendar/RangeCalendarGridBody.vue
  front_end/src/components/ui/range-calendar/RangeCalendarGridHead.vue
  front_end/src/components/ui/range-calendar/RangeCalendarGridRow.vue
  front_end/src/components/ui/range-calendar/RangeCalendarHeadCell.vue
  front_end/src/components/ui/range-calendar/RangeCalendarHeader.vue
  front_end/src/components/ui/range-calendar/RangeCalendarHeading.vue
  front_end/src/components/ui/range-calendar/RangeCalendarNextButton.vue
  front_end/src/components/ui/range-calendar/RangeCalendarPrevButton.vue
  front_end/src/components/ui/range-calendar/index.ts
  front_end/src/components/ui/textarea/Textarea.vue
  front_end/src/components/ui/textarea/index.ts
  front_end/src/components/views/attraction/AttractionDetail/AttractionDetail.vue
  front_end/src/components/views/myPlan/myPlans/myPlans.vue
  front_end/src/components/views/plan/PlanDetail/PlanDetail.vue
  front_end/src/components/views/plan/PlanDetail/PlanInfo.vue
  front_end/src/router/index.ts
  front_end/src/router/routes.ts
  front_end/src/services/api/domains/plan/index.ts
  front_end/src/services/api/domains/plan/types.ts
  front_end/src/services/api/endpoint.ts
  front_end/src/stores/plan.ts
  front_end/src/utils/planUtils.ts
  front_end/src/views/Attraction.vue
  front_end/src/views/MyPlan.vue
  front_end/src/views/Plan.vue
  front_end/src/views/PlanAttractionSearch.vue
  front_end/src/views/PlanDetail.vue
  front_end/src/views/PlanModify.vue
Labels: ✨ feature, 🖥️ FE

#75 [BE-FEAT] 댓글 조회 및 여행 좋아요 등록 버그 수정
  back_end/src/main/java/com/ssafy/stella_trip/attraction/controller/AttractionController.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/service/AttractionService.java
  back_end/src/main/java/com/ssafy/stella_trip/dao/attraction/AttractionDAO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/controller/PlanController.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/service/PlanService.java
  back_end/src/main/resources/mappers/Attraction.xml
Labels: 🐞 bugfix, 🗄️ BE

#79 Develop to Main
  back_end/src/main/java/com/ssafy/stella_trip/attraction/controller/FeaturedController.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/AttractionDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/response/FeaturedAttractionResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/dto/response/FeaturedTagResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/attraction/service/FeaturedService.java
  back_end/src/main/java/com/ssafy/stella_trip/dao/featured/FeaturedDAO.java
  back_end/src/main/java/com/ssafy/stella_trip/dao/stella/StellaDAO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/dto/response/RouteResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/service/PlanService.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/controller/StellaController.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/dto/StellaDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/dto/request/StellaRequestDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/dto/response/StellaResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/exception/StellaExceptionHandler.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/exception/StellaNotFoundException.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/service/StellaService.java
  back_end/src/main/resources/mappers/Featured.xml
  back_end/src/main/resources/mappers/Stella.xml
Labels: ✨ feature, 🗄️ BE

#80 [BE-FEAT] 내 여행계획 조회 추가
  back_end/src/main/java/com/ssafy/stella_trip/dao/plan/PlanDAO.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/controller/PlanController.java
  back_end/src/main/java/com/ssafy/stella_trip/plan/service/PlanService.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/controller/StellaController.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/dto/StellaDTO.java
  back_end/src/main/resources/mappers/Plan.xml
  back_end/src/main/resources/mappers/Stella.xml
Labels: ✨ feature, 🗄️ BE

#77 [FE-FEAT] 여행계획 및 여행지 api 연동
  front_end/src/components/NavigationBar/NavigationBar.vue
  front_end/src/components/card/AttractionCard/AttractionCard.vue
  front_end/src/components/card/PlanCard/PlanCard.vue
  front_end/src/components/common/LikeButton/LikeButton.vue
  front_end/src/components/common/Tag/Tag.vue
  front_end/src/components/ui/slider/DualSlider.vue
  front_end/src/components/ui/slider/Slider.vue
  front_end/src/components/ui/slider/index.ts
  front_end/src/components/views/attraction/AttractionDetail/AttractionDetail.vue
  front_end/src/components/views/attraction/AttractionFilter.vue
  front_end/src/components/views/attraction/FilteredAttractions/FilteredAttractions.vue
  front_end/src/components/views/plan/FilteredPlans/FilteredPlans.vue
  front_end/src/components/views/plan/PlanDetail/PlanDetailContent.vue
  front_end/src/components/views/plan/PlanDetail/PlanInfo.vue
  front_end/src/components/views/plan/PlanDetail/index.ts
  front_end/src/components/views/plan/PlanFilter.vue
  front_end/src/composables/useAttractionFilter.ts
  front_end/src/composables/useMapState.ts
  front_end/src/composables/usePlanFilter.ts
  front_end/src/constants/constant.ts
  front_end/src/services/api/domains/attraction/index.ts
  front_end/src/services/api/domains/attraction/types.ts
  front_end/src/services/api/domains/plan/index.ts
  front_end/src/services/api/domains/plan/types.ts
  front_end/src/services/api/endpoint.ts
  front_end/src/services/api/interceptors.ts
  front_end/src/services/api/types.ts
  front_end/src/utils/util.ts
  front_end/src/views/Attraction.vue
  front_end/src/views/Plan.vue
  front_end/src/views/PlanAttractionSearch.vue
  front_end/src/views/PlanDetail.vue
  package-lock.json
Labels: ✨ feature, 🖥️ FE

#83 [FE-FEAT] 메인화면, 여행지, 여행 계획 페이지 api 연동
  front_end/src/components/NavigationBar/NavigationBar.vue
  front_end/src/components/common/Tag/Tag.vue
  front_end/src/components/views/main/AttractionsSection/AttractionsSection.vue
  front_end/src/components/views/main/PopularTagsSection/PopularTagsSection.vue
  front_end/src/components/views/main/TagOverviewSection.vue
  front_end/src/components/views/plan/PlanFilter.vue
  front_end/src/constants/constant.ts
  front_end/src/services/api/domains/attraction/index.ts
  front_end/src/services/api/domains/attraction/types.ts
  front_end/src/services/api/domains/plan/index.ts
  front_end/src/services/api/domains/plan/types.ts
  front_end/src/services/api/endpoint.ts
  front_end/src/views/Attraction.vue
  front_end/src/views/Plan.vue
Labels: ✨ feature, 🖥️ FE

#86 [FE-FEAT] 별자리 props로 변경, 여행 계획 공유 플로우
  front_end/src/components/MainConstellationCard/ConstellationComponent.vue
  front_end/src/components/MainConstellationCard/MainConstellationCard.stories.ts
  front_end/src/components/MainConstellationCard/MainConstellationCard.vue
  front_end/src/components/NavigationBar/NavigationBar.vue
  front_end/src/components/card/PlanCard/PlanCard.vue
  front_end/src/components/card/StellaCard/StellaCard.stories.ts
  front_end/src/components/card/StellaCard/StellaCard.vue
  front_end/src/components/common/Constellation/Constellation.vue
  front_end/src/components/views/home/IntroductionSection.vue
  front_end/src/components/views/main/HeroSection.vue
  front_end/src/components/views/plan/PlanDetail/PlanInfo.vue
  front_end/src/components/views/plan/PlanDetail/StellaHeader.vue
  front_end/src/components/views/plan/PlanFormModal.vue
  front_end/src/composables/useConstellationAnimation.ts
  front_end/src/router/index.ts
  front_end/src/router/routes.ts
  front_end/src/services/api/domains/plan/index.ts
  front_end/src/services/api/domains/plan/types.ts
  front_end/src/services/api/domains/stella/index.ts
  front_end/src/services/api/domains/stella/types.ts
  front_end/src/services/api/endpoint.ts
  front_end/src/stores/animation.ts
  front_end/src/views/PlanDetail.vue
  front_end/src/views/SharedPlan.vue
Labels: ✨ feature, 🖥️ FE

#87 [FE=FEAT] 마이페이지 기본 틀 완성
  front_end/src/components/NavigationBar/NavigationBar.vue
  front_end/src/components/views/myPage/FavoriteAttraction.vue
  front_end/src/components/views/myPage/FavoritePlan.vue
  front_end/src/router/index.ts
  front_end/src/router/routes.ts
  front_end/src/services/api/domains/attraction/index.ts
  front_end/src/services/api/domains/user/index.ts
  front_end/src/services/api/domains/user/types.ts
  front_end/src/services/api/endpoint.ts
  front_end/src/views/MyPage.vue
Labels: ✨ feature, 🖥️ FE

#98 [BE/FE-FEAT] 마이페이지 자신의 카드 조회
  back_end/src/main/java/com/ssafy/stella_trip/dao/stella/StellaDAO.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/controller/StellaController.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/dto/StellaDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/dto/response/StellaListResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/dto/response/StellaResponseDTO.java
  back_end/src/main/java/com/ssafy/stella_trip/stella/service/StellaService.java
  back_end/src/main/resources/mappers/Stella.xml
  front_end/src/components/views/myPage/MyCard.vue
  front_end/src/components/views/myPage/MyCardContellationComponent.vue
  front_end/src/components/views/myPage/MyCardList.vue
  front_end/src/services/api/domains/stella/index.ts
  front_end/src/services/api/domains/stella/types.ts
  front_end/src/services/api/endpoint.ts
  front_end/src/views/MyPage.vue
Labels: ✨ feature, 🖥️ FE, 🗄️ BE

#99 [FE-FIX] 버그 수정
  front_end/src/components/NavigationBar/NavigationBar.vue
  front_end/src/components/card/TagCard/TagCard.vue
  front_end/src/components/views/main/HeroSection.vue
  front_end/src/components/views/plan/PlanFilter.vue
Labels: 🐞 bugfix, 🖥️ FE
